name: Linux

on: [push, pull_request]

jobs:
  blender-ubuntu-20_04:
    name: Ubuntu 20.04 Default Blender
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: sudo apt install blender
    - name: package add-on
      run: make
    - name: install blender plugin
      run: blender -b --python scripts/install.py --python-exit-code 1
